/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        primary: "#7D0A0A",
        secondary: "#5c5f61",
        tertiary: "#262d30",
        charcoal: "#191c1e",
        background: "#f9f9f9",
        surface: "#f9f9f9",
        "surface-soft": "#fbf5f4",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        outline: "#8b716f",
        "outline-variant": "#debfbc",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#57413f",
        "on-background": "#1a1c1c",
        "on-primary": "#ffffff",
        "on-primary-container": "#ff8f86",
        "on-primary-fixed": "#410003",
        "on-primary-fixed-variant": "#86201f",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#626567",
        "on-secondary-fixed": "#191c1e",
        "on-secondary-fixed-variant": "#444749",
        "secondary-container": "#e1e3e5",
        "secondary-fixed": "#e1e3e5",
        "secondary-fixed-dim": "#c5c7c9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#a9afb3",
        "on-tertiary-fixed": "#161d1f",
        "on-tertiary-fixed-variant": "#41484b",
        "tertiary-container": "#3c4346",
        "tertiary-fixed": "#dde3e7",
        "tertiary-fixed-dim": "#c1c8cb",
        "primary-container": "#801b1b",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb3ad",
        "inverse-primary": "#ffb3ad",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "surface-tint": "#a73834",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        cream: "#fff9f8"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px"
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
